# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ec2-user/s3/S3C++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ec2-user/s3/S3C++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/s3/S3C++/CMakeFiles /home/ec2-user/s3/S3C++//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/s3/S3C++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named S3C++

# Build rule for target.
S3C++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 S3C++
.PHONY : S3C++

# fast build rule for target.
S3C++/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/build
.PHONY : S3C++/fast

#=============================================================================
# Target rules for targets named leveldb

# Build rule for target.
leveldb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldb
.PHONY : leveldb

# fast build rule for target.
leveldb/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/leveldb.dir/build.make leveldb/CMakeFiles/leveldb.dir/build
.PHONY : leveldb/fast

#=============================================================================
# Target rules for targets named leveldbutil

# Build rule for target.
leveldbutil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldbutil
.PHONY : leveldbutil

# fast build rule for target.
leveldbutil/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/leveldbutil.dir/build.make leveldb/CMakeFiles/leveldbutil.dir/build
.PHONY : leveldbutil/fast

#=============================================================================
# Target rules for targets named leveldb_tests

# Build rule for target.
leveldb_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldb_tests
.PHONY : leveldb_tests

# fast build rule for target.
leveldb_tests/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/leveldb_tests.dir/build.make leveldb/CMakeFiles/leveldb_tests.dir/build
.PHONY : leveldb_tests/fast

#=============================================================================
# Target rules for targets named c_test

# Build rule for target.
c_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_test
.PHONY : c_test

# fast build rule for target.
c_test/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/c_test.dir/build.make leveldb/CMakeFiles/c_test.dir/build
.PHONY : c_test/fast

#=============================================================================
# Target rules for targets named env_posix_test

# Build rule for target.
env_posix_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 env_posix_test
.PHONY : env_posix_test

# fast build rule for target.
env_posix_test/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/env_posix_test.dir/build.make leveldb/CMakeFiles/env_posix_test.dir/build
.PHONY : env_posix_test/fast

#=============================================================================
# Target rules for targets named db_bench

# Build rule for target.
db_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 db_bench
.PHONY : db_bench

# fast build rule for target.
db_bench/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/CMakeFiles/db_bench.dir/build.make leveldb/CMakeFiles/db_bench.dir/build
.PHONY : db_bench/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/googletest/googlemock/CMakeFiles/gmock.dir/build.make leveldb/third_party/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make leveldb/third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make leveldb/third_party/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build.make leveldb/third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/benchmark/src/CMakeFiles/benchmark.dir/build.make leveldb/third_party/benchmark/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) $(MAKESILENT) -f leveldb/third_party/benchmark/src/CMakeFiles/benchmark_main.dir/build.make leveldb/third_party/benchmark/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

algorithm/merge.o: algorithm/merge.cpp.o
.PHONY : algorithm/merge.o

# target to build an object file
algorithm/merge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/algorithm/merge.cpp.o
.PHONY : algorithm/merge.cpp.o

algorithm/merge.i: algorithm/merge.cpp.i
.PHONY : algorithm/merge.i

# target to preprocess a source file
algorithm/merge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/algorithm/merge.cpp.i
.PHONY : algorithm/merge.cpp.i

algorithm/merge.s: algorithm/merge.cpp.s
.PHONY : algorithm/merge.s

# target to generate assembly for a file
algorithm/merge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/algorithm/merge.cpp.s
.PHONY : algorithm/merge.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/main.cpp.s
.PHONY : main.cpp.s

queryMethod/query.o: queryMethod/query.cpp.o
.PHONY : queryMethod/query.o

# target to build an object file
queryMethod/query.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/queryMethod/query.cpp.o
.PHONY : queryMethod/query.cpp.o

queryMethod/query.i: queryMethod/query.cpp.i
.PHONY : queryMethod/query.i

# target to preprocess a source file
queryMethod/query.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/queryMethod/query.cpp.i
.PHONY : queryMethod/query.cpp.i

queryMethod/query.s: queryMethod/query.cpp.s
.PHONY : queryMethod/query.s

# target to generate assembly for a file
queryMethod/query.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/queryMethod/query.cpp.s
.PHONY : queryMethod/query.cpp.s

sort/sort.o: sort/sort.cpp.o
.PHONY : sort/sort.o

# target to build an object file
sort/sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/sort/sort.cpp.o
.PHONY : sort/sort.cpp.o

sort/sort.i: sort/sort.cpp.i
.PHONY : sort/sort.i

# target to preprocess a source file
sort/sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/sort/sort.cpp.i
.PHONY : sort/sort.cpp.i

sort/sort.s: sort/sort.cpp.s
.PHONY : sort/sort.s

# target to generate assembly for a file
sort/sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/sort/sort.cpp.s
.PHONY : sort/sort.cpp.s

translate/translate.o: translate/translate.cpp.o
.PHONY : translate/translate.o

# target to build an object file
translate/translate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/translate/translate.cpp.o
.PHONY : translate/translate.cpp.o

translate/translate.i: translate/translate.cpp.i
.PHONY : translate/translate.i

# target to preprocess a source file
translate/translate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/translate/translate.cpp.i
.PHONY : translate/translate.cpp.i

translate/translate.s: translate/translate.cpp.s
.PHONY : translate/translate.s

# target to generate assembly for a file
translate/translate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/S3C++.dir/build.make CMakeFiles/S3C++.dir/translate/translate.cpp.s
.PHONY : translate/translate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... S3C++"
	@echo "... benchmark"
	@echo "... benchmark_main"
	@echo "... c_test"
	@echo "... db_bench"
	@echo "... env_posix_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... leveldb"
	@echo "... leveldb_tests"
	@echo "... leveldbutil"
	@echo "... algorithm/merge.o"
	@echo "... algorithm/merge.i"
	@echo "... algorithm/merge.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... queryMethod/query.o"
	@echo "... queryMethod/query.i"
	@echo "... queryMethod/query.s"
	@echo "... sort/sort.o"
	@echo "... sort/sort.i"
	@echo "... sort/sort.s"
	@echo "... translate/translate.o"
	@echo "... translate/translate.i"
	@echo "... translate/translate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

